### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by plafosse** [Vector35/deprecated_python_debugger#10]

**Comment by meme** [comment]
What exactly is Android support in this case? Android uses `gdbserver` or `lldbserver` for remote debugging support which is already supported by this tool.

**Comment by psifertex** [comment]
The current gdbserver isn't configurable (IP and port) and there's a few hard-coded x86 things in the CLI that need to be abstracted. Not a whole lot needs to be done, but once those are complete we can resolve this issue.

**Comment by lwerdna** [comment]
This is mostly done, but module listing (issue #45) doesn't work and tests are nonexistent currently.
