### ISSUE TITLE
Debugger Setting Registration Broken

### ISSUE THREAD

**Issue by bpotchik** [Vector35/deprecated_python_debugger#102]
Setting: debugger.extra_annotations already registered!

**Comment by lwerdna** [comment]
Is this tested with latest? I thought I'd gotten rid of this with c01bd4ba82eaffbca0ed65a3398e1d5f4a00e336

**Comment by bpotchik** [comment]
Oh it looks like it may be? I filed it on behalf of grego.

**Comment by lwerdna** [comment]
I checked with that very lazy guy on slack, he had old version.
