### ISSUE TITLE
remote debugging on non-windows platform to a windows platform results in an error

### ISSUE THREAD

**Issue by psifertex** [Vector35/deprecated_python_debugger#105]
This issue tracks the error which should be more gracefully handled:

```OSError: dlopen(/Users/.../Library/Application Support/Binary Ninja/repositories/official/plugins/Vector35_debugger/dbgengadapt\dbgengadapt.dll, 6): image not found```

**Comment by psifertex** [comment]
Note that this is not the same as #106 which is adding full support, this would just result in better documentation/graceful error handling if it's attempted currently.

**Comment by theguly** [comment]
thanks for opening this issue.
as you can expect, we have the same behaviour from a linux host

**Comment by lwerdna** [comment]
Windows remote debugging was mistakenly added as an adapter type enum. I know remote kernel debugging is a thing (how could a paused kernel schedule the debug process on the same machine?) but I don't think remote debugging of usermode programs is.
