### ISSUE TITLE
settings not saved

### ISSUE THREAD

**Issue by psifertex** [Vector35/deprecated_python_debugger#108]
It looks like at least some debugger settings (such as `Request Terminal Emulator`) are not saved and need to be manually set at each launch.

**Comment by lwerdna** [comment]
Metadata alone is not sufficient to trigger a save. I'm debating whether or not to hack it, by doing something like settings and unsetting a comment.

```
>>> bv.store_metadata("integer", 1337)
>>> bv.query_metadata("integer")
1337
~~~~ close bndb, reopen bndb ~~~~
>>> bv.query_metadata("integer")
...
KeyError: 'integer'
```

**Comment by lwerdna** [comment]
https://github.com/Vector35/binaryninja/issues/117

**Comment by lwerdna** [comment]
You must manually file->save or cmd+s or whatever. Metadata alone won't trigger the bndb save, but if the save occurs the debugger settings including the request of the terminal emulator will be stored.

https://github.com/Vector35/binaryninja-api/issues/1174
