### ISSUE TITLE
Python2 insted of python3

### ISSUE THREAD

**Issue by destrudos** [Vector35/deprecated_python_debugger#112]
Hello~!
I have a problem both on windows and linux platform. after copying the debugger plugin to the plugins folder and starting app the BN shows me this error:

`Traceback (most recent call last):
  File "C:\Users\Dominik\AppData\Roaming\Binary Ninja\plugins\debugger-master\__init__.py", line 47, in <module>
    raise Exception("Debugger requires Python 3.6 or greater")
Exception: Debugger requires Python 3.6 or greater
Python plugin 'debugger-master' could not be loaded
`

of course i have python v3.8 on the system:

`Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import sys
print(sys.version_info)
sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)`

in addition, when I added the following line to the __init__ plugin file:
print(sys.version_info)
I recived:
`sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)
`
An impropper Python version!
What can I do with thiss issue?

**Comment by lwerdna** [comment]
In settings -> python -> python interpreter check that it points to your 3.8.3 python instead of the 2.7.10 one.

**Comment by destrudos** [comment]
Works like a dream! Stupidly I did not checked this before. Anyway, God bless you, Iwerdna.
