### ISSUE TITLE
Binary Ninja Crashes with Debugger Plugin Installed on macOS 10.16

### ISSUE THREAD

**Issue by bpotchik** [Vector35/deprecated_python_debugger#117]

**Comment by psifertex** [comment]
FYI, I'm unable to reproduce a crash. I can successfully use the latest debugger with the latest dev on Big Sur. Note that debugging system binaries is not possible, I recommend building some of the binaries in testbins and using those to test:

```
cd ~/Library/Application\ Support/Binary\ Ninja/repositories/official/plugins/Vector35_debugger/testbins
make -f Makefile-macos
```

You'll need a brew installed `nasm` if you want to build them all, but only need one for testing.

**Comment by bpotchik** [comment]
Only steps I know to repro are open a file. Close it. Then reopen the file.

**Comment by bpotchik** [comment]
This was with latest dev and latest Debugger installed.

**Comment by psifertex** [comment]
To be clear, this has been resolved for some time.
