### ISSUE TITLE
Clicking a breakpoint in the BreakpointsWidget throws log error

### ISSUE THREAD

**Issue by hanssl** [Vector35/deprecated_python_debugger#120]
Steps to reproduce:
1. Open a binary in the debugger.
2. Click a link in the BreakpointsWidget
3. Observe the error in the log window: AttributeError: module 'binaryninjaui' has no attribute 'SelectionColor'

![Screenshot from 2021-01-11 13-04-26](https://user-images.githubusercontent.com/649957/104232727-fa904900-540d-11eb-8dd9-9239bb4d671b.png)

**Comment by lwerdna** [comment]
Fixed in: https://github.com/Vector35/debugger/commit/fb6a0e20869c625b4a27d12acaef508b10032746#diff-829eaf2991fd595fe40e3cb1ad5b5ebc90c8805bb1c955ecf17aa900bef6b1b9
