### ISSUE TITLE
DisassemblyContainer.getGraphType() missing in v2.3.2660

### ISSUE THREAD

**Issue by hanssl** [Vector35/deprecated_python_debugger#125]
The ControlsWidget calls 'disasm.getGraphType()' from perform_step_into_li() and perform_step_over_li().  The DisassemblyContainer class does not have the getGraphType() function in 2.3.2660.

**Comment by hanssl** [comment]
Correction.  The code looks like:

disasm = self.debug_state.ui.debug_view.binary_editor.getDisassembly()
graph_type = disasm.getGraphType()

The calls to .getDisassembly() returns a DisassemblyView object.

The DisassemblyView object in v2.3.2660 does not have the getGraphType() function.

**Comment by bpotchik** [comment]
This was fixed back in November but we were missing a Plugin version bump to 1.3.2.
