### ISSUE TITLE
gdbserver detection is broken

### ISSUE THREAD

**Issue by psifertex** [Vector35/deprecated_python_debugger#130]
https://github.com/Vector35/debugger/blob/master/gdb.py#L33-L34

->

```
        path_gdbserver = shutil.which('gdbserver')
        if not path_gdbserver:
```

(`shutil.which` already returns none if it can't find the path, `os.path.exists` is redundant and will except if passed None.

**Comment by lwerdna** [comment]
fixed at f96bc802831792ba5c772a62b1f3534218087019
