### ISSUE TITLE
Debugger (on Windows) is Broken since 3.x release

### ISSUE THREAD

**Issue by marpie** [Vector35/deprecated_python_debugger#143]
Using the debugger on windows is not possible on version `3.0.3245-dev (Build ID e4643153)` using the store version of the Debugger.

![image](https://user-images.githubusercontent.com/703785/152305648-8750b1f9-1eee-456c-82cb-a1131be928fd.png)

The following two changes fixes the bug:

```diff
diff --git a/DebugView.py b/DebugView.py
index d41ccc0..2b5c713 100644
--- a/DebugView.py
+++ b/DebugView.py
@@ -305,7 +305,7 @@ class DebugView(QWidget, View):
                # Append header line
                tokens = [InstructionTextToken(InstructionTextTokenType.TextToken, "(Code not backed by loaded file, showing only raw disassembly)")]
                contents = DisassemblyTextLine(tokens, start_ip)
-               if (major == 2):
+               if (major >= 2):
                        line = LinearDisassemblyLine(LinearDisassemblyLineType.BasicLineType, None, None, contents)
                else:
                        line = LinearDisassemblyLine(LinearDisassemblyLineType.BasicLineType, None, None, 0, contents)
@@ -353,7 +353,7 @@ class DebugView(QWidget, View):

                        # Convert to linear disassembly line
                        contents = DisassemblyTextLine(tokens, line_addr, color=color)
-                       if (major == 2):
+                       if (major >= 2):
                                line = LinearDisassemblyLine(LinearDisassemblyLineType.CodeDisassemblyLineType, None, None, contents)
                        else:
                                line = LinearDisassemblyLine(LinearDisassemblyLineType.CodeDisassemblyLineType, None, None, 0, contents)
```

**Comment by psifertex** [comment]
Thanks! The right fix is just to remove that check entirely since I'm not sure what it was even _supposed_ to do and we don't have py2 support anymore, but I've added that and triggered a new release. I haven't done a lot of testing but it's definitely not worse than before. :-) 

Python debugger is on a bit of life-support as we're very close to getting out the new native rewrite, but hopefully this works for you in the meantime!

**Comment by psifertex** [comment]
(Also, I updated the version in the plugin manager so you should be able to use the version there as opposed to having to manually clone the repo)
