### ISSUE TITLE
PySide6/QtCore.abi3.so: Symbol not found

### ISSUE THREAD

**Issue by Hellstormer00** [Vector35/deprecated_python_debugger#145]
On startup I get the following message in the log. I also don't find the option _Debugger_ in the Dropdown menu.

```
dlopen(/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python3/PySide6/QtCore.abi3.so, 2): Symbol not found: _PyIndex_Check
  Referenced from: /Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python3/PySide6/QtCore.abi3.so
  Expected in: flat namespace
 in /Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python3/PySide6/QtCore.abi3.so
Could not initialize UI, using headless mode only
Loaded python3 plugin 'debugger'
```

The File QtCore.abi3.so exists in that path.

My System:
MacOS 11.4 BigSur

**Comment by psifertex** [comment]
What version of Binary Ninja is this? Do other UI plugins work? Try the "snippets" plugin in the plugin manager.

**Comment by Hellstormer00** [comment]
The BN version is 3.0.3233.
No the snippets plugin doesn't work too with the same error

**Comment by psifertex** [comment]
Can you please try with the latest development release and see if it's fixed? https://docs.binary.ninja/getting-started.html#updates

**Comment by Hellstormer00** [comment]
I tried. My binja version is "3.0.3301-dev personal". I'm still getting the same error. Is my PySide6 installation broken?

**Comment by psifertex** [comment]
You shouldn't have to install Pyside6 at all. Have you installed a separate copy? I would think our built in libraries should be loaded first.

**Comment by Hellstormer00** [comment]
The issue occured before I installed it by myself. I installed it myself, because I thought it was a dependency I that I had to manually install.

**Comment by Hellstormer00** [comment]
I found the error. In the past there was some issue with python, so I chose another interpreter on the system in the settings. (Python 3.7) Apparently I shouldn't have done that

**Comment by psifertex** [comment]
Other systems should work fine as long as they're also 64bit and have the same packages installed, but glad you got it working!
