### ISSUE TITLE
Add "IL mode" for stepping

### ISSUE THREAD

**Issue by joshwatson** [Vector35/deprecated_python_debugger#20]
When stepping, if the user is in LLIL or MLIL view, add a setting so that the debugger can step over optimized-away disassembly and just step between each LLIL/MLIL instruction, similar to "source mode" in WinDbg

**Comment by psifertex** [comment]
This probably shouldn't be a setting but rather just the normal behavior once implemented. There's no reason you'd want to step into an address you couldn't see in that view. But it's a very good suggestion!

**Comment by CouleeApps** [comment]
Updated workflow: step into / step over will use the currently selected IL, and if you want assembly stepping there is a dropdown menu for each button with that option.
