### ISSUE TITLE
Tell the user when the debugged process raises an exception

### ISSUE THREAD

**Issue by joshwatson** [Vector35/deprecated_python_debugger#25]
I intentionally tried to crash the running program, and instead of telling me anything, it just keeps trying to resume when I step or resume, rather than alerting me that the program has crashed

**Comment by lwerdna** [comment]
Exception reporting isn't complete, but now basic exception reporting exists on all platforms.

Prior, any of the blocking calls (go, step, step_into) would return only DebugAdapter.STOP_REASON.PROCESS_EXITED or DebugAdapter.STOP_REASON.BREAKPOINT.

Now, you should get ACCESS_VIOLATION, SINGLE_STEP, CALCULATION,  ILLEGAL_INSTRUCTION when supported by the target, and there's much variation. For example on macos, single step still returns BREAKPOINT. On arm and aarch64, I can't get it to divide by 0. Illegal instruction is difficult to get too, most target platforms return access violation. I did my best to verify these cases with other debuggers.

Please open another issue if there's a particular exception not being reported on a certain platform.
