### ISSUE TITLE
Navigating debug view

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/deprecated_python_debugger#32]
Related to #21, currently the debug view does not respond when the user tries to navigate to functions. Need some way to determine if they are navigating to code (show in the left view) or local data (linear view in the left view?) or memory (show in the right view).

Also need to figure out how history works

**Comment by Ben-Lichtman** [comment]
My suggestion is to potentially combine the static view with the debugger, where all the static analysis is superimposed on top of the memory overview and placed in the .text segment as it should be; on top of the raw bytes. then make the rest of the memory view navigable as if it was an extension of the linear view.

Though I'm not sure how practical it would be.

**Comment by CouleeApps** [comment]
Fixed as of the undo / navigation updates in ee3df13e
