### ISSUE TITLE
automatic code discovery

### ISSUE THREAD

**Issue by psifertex** [Vector35/deprecated_python_debugger#39]
Two important features we plan:

1. when single stepping through a call and the call-target is a function in the current view's segments that we do not have a function for, create the function
2. likewise for discovering other indirect control flow such as jump targets (though obviously not creating a function but using  `set_user_indirect_branches`

**Comment by CouleeApps** [comment]
As of c9b0f909 calls will create new functions when single-stepping, and jmps will add their targets to the current function
