### ISSUE TITLE
cannot get modules/solib map on remote gdb targets

### ISSUE THREAD

**Issue by lwerdna** [Vector35/deprecated_python_debugger#45]
The current method uses a read of /proc/<pid>/maps which won't work on remote targets.

This also prevents finding the location of the module being debugged and resolving ASLR'd addresses.

**Comment by lwerdna** [comment]
Spying on gdb/gdbserver communication from the NDK, they're also reading /proc/pid/maps but using the Host I/O within RSP to read the remote side: https://sourceware.org/gdb/current/onlinedocs/gdb/Host-I_002fO-Packets.html

This shouldn't be too hard to get working, but I'm concerned about latency if `mem_modules()` is called frequently.

**Comment by CouleeApps** [comment]
At the moment, `mem_modules()` is called once per step. If there is a way to get notified when a module is loaded/unloaded, we can make it only called then.
