### ISSUE TITLE
Initialization in DllMain

### ISSUE THREAD

**Issue by mrexodia** [Vector35/deprecated_python_debugger#56]
I noticed [here](https://github.com/Vector35/debugger/blob/b81d10e61db47eea4a335839b2e735e285d6c9b4/dbgengadapt/dbgengadapt.cpp#L1192) that you are initializing a COM interface inside of `DllMain`, which is likely to cause issues and is not good practice.

https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain says:

> There are significant limits on what you can safely do in a DLL entry point. See General Best Practices for specific Windows APIs that are unsafe to call in DllMain. If you need anything but the simplest initialization then do that in an initialization function for the DLL. You can require applications to call the initialization function after DllMain has run and before they call any other functions in the DLL.

See https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices for more information about the potential issues.

**Comment by lwerdna** [comment]
That's true, thanks. So far it's not caused problems, so probably it will be treated as low priority for when there's some free time.
