### ISSUE TITLE
"Run" menu item is disabled until switching to the debugger view

### ISSUE THREAD

**Issue by psifertex** [Vector35/deprecated_python_debugger#63]
The "run" button is disabled unless you enable the debugger view, but once you've navigated to it once you can change back to another view and it will work.

Screenshots in order:

<img width="828" alt="Screen Shot 2020-04-02 at 10 27 28 PM" src="https://user-images.githubusercontent.com/140215/78317787-3cac6600-7531-11ea-887a-860ab6ca4f7f.png">
<img width="848" alt="Screen Shot 2020-04-02 at 10 27 39 PM" src="https://user-images.githubusercontent.com/140215/78317794-3f0ec000-7531-11ea-8cb7-48b0dff9a8a3.png">
<img width="866" alt="Screen Shot 2020-04-02 at 10 27 56 PM" src="https://user-images.githubusercontent.com/140215/78317799-4209b080-7531-11ea-9fd1-15e24097116a.png">

**Comment by lwerdna** [comment]
The run menu item essentially clicks the run button in the DebugView, which doesn't exist until "Debugger" is selected from the binary views.

```
def cb_process_run(bv):
	...
	debug_state.ui.debug_view.controls.actionRun.trigger() # <-- HERE
```

Prior to the first click, the UI calls valid_process_run() which detects debug_state.ui as None and returns False resulting in greyed out menu item.

Can we do what the click does, or synthesize it somehow? Not easily. Upon "Debugger" click, some execution originating in c++ land calls DebugViewType.create() with a binary view and a view_frame parameter.

```
class DebugViewType(ViewType):
	# executed at plugin load time from from ui.py ViewType.registerViewType()
	def __init__(self):
		print( super(DebugViewType, self).__init__ )
		super(DebugViewType, self).__init__("Debugger", "Debugger")

	def getPriority(self, data, filename):
		return 1

	# executed when user clicks "Debugger" from dropdown with binary views
	def create(self, data, view_frame):
		return DebugView(view_frame, data)
```

A python stack trace at this point shows no callers. None of my attempts at being tricky have been successful.

**Comment by lwerdna** [comment]
In other words, I think is behavior is by design. Maybe a future `ui.switch_to_binary_view("Hex Editor")` or `ui.switch_to_binary_view("Linear Disassembly")` api call would be cool.

**Comment by lwerdna** [comment]
Brian has the solution:
```
from binaryninjaui import DockHandler, DockContextHandler, UIActionHandler, ViewFrame
from PySide2 import QtCore
from PySide2.QtCore import Qt
from PySide2.QtWidgets import QApplication, QHBoxLayout, QVBoxLayout, QLabel, QWidget
def switch_view():
	dh = DockHandler.getActiveDockHandler()
	vf = dh.getViewFrame()
	vf.setViewType("Hex:Mach-O")
execute_on_main_thread_and_wait(switch_view)
```
