### ISSUE TITLE
Debugger doesn't work unless you go to View>Debugger first.

### ISSUE THREAD

**Issue by ManuelBerrueta** [Vector35/deprecated_python_debugger#65]
Bug where the debugger doesn't let you run it form the Tools>Debugger>Process>Run, you must go to the View>Debugger first. 

This is on Windows 10. Tried it with both Python 3.7 and 3.8 with the same results.

It also freezes randomly with some binaries and gets an "Exception: Cannot resolve relative address:" with others.

![image](https://user-images.githubusercontent.com/28192344/78408239-7164ff80-75bb-11ea-87b4-a1815bfca8af.png)

**Comment by lwerdna** [comment]
Could you make sure you have the latest? Just a couple hours before you filed this, there was a fix for the issue about running from the menu. https://github.com/Vector35/debugger/issues/63

Do you have a binary that demonstrates the "Cannot resolve relative address" error?

**Comment by ManuelBerrueta** [comment]
Hello you are correct! I was working with Jordan on this and he even posted on the chat, sorry about that!
