### ISSUE TITLE
Display stderr from running gdbserver/lldbserver

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/deprecated_python_debugger#69]
Currently these are printed to sys.stderr and any errors they send are lost.

**Comment by lwerdna** [comment]
The debugserver (lldb server) is smart enough to capture and relay it to us with an `O` packet (https://sourceware.org/gdb/current/onlinedocs/gdb/Stop-Reply-Packets.html#Stop-Reply-Packets) but not gdbserver. I'm looking into using a pseudo terminal master/slave pair or just launching a shell (or giving the user the option to!) upon execution.

![macos_stderr](https://user-images.githubusercontent.com/474191/83061196-9b222c00-a02a-11ea-9d3a-0c81ec32a251.png)

**Comment by lwerdna** [comment]
The recommended interaction now is to select "request terminal emulator" from debugger options, then debug the program from binja. In this new terminal, you can see all stdout and stderr.

Debugger console is commented out for now. In the future we may have a terminal emulator built into the debugger but for now executing a system one works well.
