### ISSUE TITLE
Renamed windows exe files are not found in the modules list

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/deprecated_python_debugger#76]
Some exe files contain their original filename within the exe and will show up under that filename in the adapter modules list, even if the actual file has since been renamed.

Steps to reproduce:  
OS: Windows 10 / BN Latest Dev / Debugger master branch
1. Copy calc.exe from C:\Windows\System32 to Desktop
2. Rename calc.exe to renamed.exe
3. Run renamed.exe in the debugger

Running `list(dbg.modules)` in the console after launch shows renamed.exe loaded under the module `calc.exe`. We need to either check for the original name (calc.exe) in the ui plugin or have the adapter respond with the updated name (renamed.exe).

**Comment by lwerdna** [comment]
The windows debugging subsystem might prioritize the self-proclaimed name in the PE's [export directory table](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#export-directory-table). I'll look a bit further because I would prefer the real path if I were an analyst.

As an aside, calc is [no longer a lean, minimal exe](https://github.com/microsoft/calculator/issues/164) like it once was suitable for testing.

**Comment by lwerdna** [comment]
The module enumerating function is _supposed_ to return "image name", "module name", and "loaded module name" where the first has the full path, but in a couple tests, "image name" doesn't contain a path for the debugged program and ntdll. The same happens in windbg with `lm` (loaded modules) command.

**Comment by lwerdna** [comment]
Upon exec/attach, we now use the `DebugAdapter.target_base()` API and resolve the module with `DebuggerModules.get_module_for_addr()`. This should avoid problems when we tried to use the original name (from `bv.file.original_filename`) and `DebuggerModules.resolve_path()` after the name had changed.

If the returned module is NOT the one specified in the bv path or the temp file path, a mapping is created in the DebuggerModules object to return the actual path. So for the UI, this is fixed.

**Comment by lwerdna** [comment]
In headless, if you use a DebugAdapter, you'll get what the OS/debugger returns. This is by design (DebugAdapter should remain low level and do minimal translation) and you have the option of overriding what the OS returns if you like.
