### ISSUE TITLE
Documentation for testbin build tools 

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/deprecated_python_debugger#81]
In case someone wants to build the test binaries, we should provide a list of tools they need.

Here's what I've been using (might be able to get more minimal than this):

macOS:
- `xcode-select --install` for commandline build tools
- nasm

Windows (msvc runtime)
- MSVC Windows SDK  / C++ development environment
- nasm

Windows (mingw)
- ???

Linux:
- gcc-multilib
- nasm

**Comment by lwerdna** [comment]
included in the manual at: https://github.com/Vector35/debugger/blob/master/documentation/Manual.md#automated-tests
