### ISSUE TITLE
Better error for first debug on macOS since boot

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/deprecated_python_debugger#87]
On the first time debugging a program since boot, macOS prompts the user to authenticate for lldb. Currently when this happens we just throw a connection refused exception. It would be nice to instead detect this behavior and pause while the user authenticates.

**Comment by lwerdna** [comment]
Do you know how to revoke lldb authorization (without rebooting) to ease testing?

**Comment by CouleeApps** [comment]
`DevToolsSecurity -disable` seems to do it
