### ISSUE TITLE
only set initial breakpoint after the "run" button is pressed

### ISSUE THREAD

**Issue by psifertex** [Vector35/deprecated_python_debugger#93]
There's no reason to set a default breakpoint on all files just because the debugger plugin is installed. The initial breakpoint should only be set after the user presses run or maybe if they switch to the debugger view.

**Comment by lwerdna** [comment]
Notes:

The tag was being placed at DebuggerState constructor in binjaplug.py which happens on executable load.

```
if self.bv and self.bv.entry_point:
	# ...
	self.breakpoints.add_offset(...)
	self.ui.breakpoint_tag_add(...)
	# ...
```

click "Run" -> perform_run_thread() in dockwidgets/ControlsWidget.py

```
            -> DebuggerState.run()
            -> DebuggerState.exec()
            -> DebuggerBreakpoints.apply() (self.breakpoints)
```
