### ISSUE TITLE
: RuntimeWarning: libshiboken: Overflow: Value 18446744073709551600 exceeds limits of type  [unsigned] "m" (8bytes).

### ISSUE THREAD

**Issue by CunningLogic** [Vector35/deprecated_python_debugger#96]
Version 2.0.2133-dev (Build ID a037596e)
commit d1cde4fc4a6c61730b701e05db92d85ffa17cffe

/home/jcase/.binaryninja/plugins/debugger/dockwidgets/DebugView.py:350: RuntimeWarning: libshiboken: Overflow: Value 18446744073709551600 exceeds limits of type  [unsigned] "m" (8bytes).
  self.binary_text.setLines(lines)

Loaded python3 plugin 'debugger'
Loaded python3 plugin 'BinjaHLILDump'
Loaded python3 plugin 'cryptoscan'
Loaded python3 plugin 'format-string-finder-binja'
Loaded python3 plugin 'bnhook'
Loaded python3 plugin 'DUMB'
Detected Little Endian endian ELF
ELF parsing took 0.037 seconds
Analysis update took 0.013 seconds
Analysis starting...
Adding section: .fini <0x8048704 - 0x8048717> for analysis.
Adding section: .init <0x80483dc - 0x80483fe> for analysis.
Adding section: .plt <0x8048400 - 0x804849f> for analysis.
Adding section: .plt.got <0x80484a0 - 0x80484a7> for analysis.
Adding section: .text <0x80484b0 - 0x8048701> for analysis.
Analysis Phase 2 created 0 functions. [x86:linux-x86]
Analysis Phase 3.0 created 1 functions [x86:linux-x86]
Analysis Phase 3.1 created 0 functions [x86:linux-x86]
Loaded signature library: /home/jcase/bin/binaryninja/signatures/linux-x86/ubuntu-bionic-i386-libgcc-7-dev.sig
Loaded signature library: /home/jcase/bin/binaryninja/signatures/linux-x86/ubuntu-xenial-i386-libc6-dev.sig
Loaded signature library: /home/jcase/bin/binaryninja/signatures/linux-x86/ubuntu-bionic-i386-libgcc-8-dev.sig
Loaded signature library: /home/jcase/bin/binaryninja/signatures/linux-x86/ubuntu-bionic-i386-libgcc-5-dev.sig
Loaded signature library: /home/jcase/bin/binaryninja/signatures/linux-x86/ubuntu-bionic-i386-libgcc-6-dev.sig
Loaded signature library: /home/jcase/bin/binaryninja/signatures/linux-x86/ubuntu-bionic-i386-libc6-dev.sig
Loaded signature library: /home/jcase/bin/binaryninja/signatures/linux-x86/ubuntu-xenial-i386-libgcc-5-dev.sig
6 functions matched total, 0 name-only matches, 0 thunks resolved, 12 functions skipped because they were too small
Analysis update took 0.016 seconds
Analysis update took 0.000 seconds
/usr/bin/gdbserver --once --no-startup-with-shell localhost:31337 /storage/CTFSolutions/ctf/pico2018/echoback/echoback
OverflowError: int too big to convert
/home/jcase/.binaryninja/plugins/debugger/dockwidgets/DebugView.py:350: RuntimeWarning: libshiboken: Overflow: Value 18446744073709551600 exceeds limits of type  [unsigned] "m" (8bytes).
  self.binary_text.setLines(lines)

**Comment by CunningLogic** [comment]
attaching binary that causes the issue

[echoback.tar.gz](https://github.com/Vector35/debugger/files/4616385/echoback.tar.gz)

**Comment by peperunas** [comment]
I'm having the same issue.

I'm using Binary Ninja `dev-2144` on Arch Linux with no other plugins activated.
The breakpoint is set at the first instruction of `main`.

```
OverflowError: int too big to convert
/home/user/.binaryninja/plugins/debugger/dockwidgets/DebugView.py:350: RuntimeWarning: libshiboken: Overflow: Value 18446744073709551600 exceeds limits of type  [unsigned] "m" (8bytes).
  self.binary_text.setLines(lines)
```

Here is the binary: 
[3step.zip](https://github.com/Vector35/debugger/files/4621667/3step.zip)

**Comment by lwerdna** [comment]
@CunningLogic @peperunas thanks for the bug report, sorry for the delay

**Comment by CunningLogic** [comment]
@lwerdna delay? dude plenty fast for me thank you.
