### ISSUE TITLE
Add support for gathering coverage information from debugger

### ISSUE THREAD

**Issue by tekwizz123** [Vector35/deprecated_python_debugger#98]
With tools like bncov and Lighthouse having support for coverage files, and the ability for the debugger to identify what parts of the code were executed, it would be great if we could also export coverage information from the debugger to better allow these tools to find out what parts of the binary were executed on different runs.

This would allow Binary Ninja to be used as an automated tool for gathering coverage information which could be useful considering automation via the API is one of its primary selling points.

**Comment by mechanicalnull** [comment]
There is some trickiness to do this correctly and robustly while not destroying performance, but I put together a starting point that may meet your need: https://github.com/mechanicalnull/binja-debugger-scripts/blob/master/debugger_block_coverage.py

**Comment by lwerdna** [comment]
this belong in a script, and mechanicalnull's demonstrates well

there's another example included in the source: https://github.com/Vector35/debugger/blob/master/examples/dacman_live_hilbert.py

which shows the basic idea
- loop over all functions (or basic blocks) with the analysis api
- set breakpoints with debugger api
- go with debugger api
- upon breakpoint hit, clear breakpoint, record coverage information
